version: "3.5"

services:
    taiga-database:
        image: postgres:12.3
        container_name: taiga-database
        restart: unless-stopped
        environment:
            POSTGRES_DB: "${POSTGRES_NAME}"
            POSTGRES_USER: "${POSTGRES_USER}"
            POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
        volumes:
            - "${VOLUME_BASE_PATH}/database/data:/var/lib/postgresql/data"
        networks:
            - taiga

    taiga-backend:
        image: taigaio/taiga-back:latest
        container_name: taiga-backend
        restart: unless-stopped
        environment:
            POSTGRES_DB: "${POSTGRES_NAME}"
            POSTGRES_USER: "${POSTGRES_USER}"
            POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
            POSTGRES_HOST: "${POSTGRES_HOST}"
            RABBITMQ_USER: "${RABBITMQ_USER}"
            RABBITMQ_PASS: "${RABBITMQ_PASSWORD}"
            TAIGA_SECRET_KEY: "${RABBITMQ_SECRET_KEY}"
            TAIGA_SITES_SCHEME: "http"
            TAIGA_SITES_DOMAIN: "localhost:9000"
            EMAIL_BACKEND: "django.core.mail.backends.smtp.EmailBackend"
            DEFAULT_FROM_EMAIL: "example@example.com"
            EMAIL_USE_TLS: "True"
            EMAIL_USE_SSL: "False"
            EMAIL_HOST: "smtp.example.com"
            EMAIL_PORT: 587
            EMAIL_HOST_USER: "example@example.com"
            EMAIL_HOST_PASSWORD: "example"
            ENABLE_TELEMETRY: "False"
        volumes:
            - "${VOLUME_BASE_PATH}/resources/static:/taiga-back/static"
            - "${VOLUME_BASE_PATH}/resources/media:/taiga-back/media"
            # - ./config.py:/taiga-back/settings/config.py
        networks:
            - taiga
        depends_on:
            - taiga-database
            - taiga-events-rabbitmq
            - taiga-async-rabbitmq

    taiga-async:
        image: taigaio/taiga-back:latest
        container_name: taiga-async
        restart: unless-stopped
        entrypoint: ["/taiga-back/docker/async_entrypoint.sh"]
        environment: 
            POSTGRES_DB: "${POSTGRES_NAME}"
            POSTGRES_USER: "${POSTGRES_USER}"
            POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
            POSTGRES_HOST: "${POSTGRES_HOST}"
            RABBITMQ_USER: "${RABBITMQ_USER}"
            RABBITMQ_PASS: "${RABBITMQ_PASSWORD}"
            TAIGA_SECRET_KEY: "${RABBITMQ_SECRET_KEY}"
        volumes:
            - "${VOLUME_BASE_PATH}/resources/static:/taiga-back/static"
            - "${VOLUME_BASE_PATH}/resources/media:/taiga-back/media"
        networks:
            - taiga
        depends_on:
            - taiga-database
            - taiga-backend
            - taiga-async-rabbitmq

    taiga-async-rabbitmq:
        image: rabbitmq:3-management-alpine
        container_name: taiga-async-rabbitmq
        restart: unless-stopped
        environment:
            RABBITMQ_DEFAULT_USER: "${RABBITMQ_USER}"
            RABBITMQ_DEFAULT_PASS: "${RABBITMQ_PASSWORD}"
            RABBITMQ_DEFAULT_VHOST: "${RABBITMQ_VHOST}"
            RABBITMQ_ERLANG_COOKIE: "${RABBITMQ_ERLANG_COOKIE}"
        volumes:
            - "${VOLUME_BASE_PATH}/rabbitmq/async:/var/lib/rabbitmq"
        networks:
            - taiga

    taiga-frontend:
        image: taigaio/taiga-front:latest
        container_name: taiga-frontend
        restart: unless-stopped
        environment:
            TAIGA_URL: "http://localhost:9000"
            TAIGA_WEBSOCKETS_URL: "ws://localhost:9000"
        networks:
            - taiga
        # volumes:
        #     - ./conf.json:/usr/share/nginx/html/conf.json

    taiga-events:
        image: taigaio/taiga-events:latest
        container_name: taiga-events
        restart: unless-stopped
        environment:
            RABBITMQ_USER: "${RABBITMQ_USER}"
            RABBITMQ_PASS: "${RABBITMQ_PASSWORD}"
            TAIGA_SECRET_KEY: "${RABBITMQ_SECRET_KEY}"
        networks:
            - taiga
        depends_on:
            - taiga-events-rabbitmq

    taiga-events-rabbitmq:
        image: rabbitmq:3-management-alpine
        container_name: taiga-events-rabbitmq
        restart: unless-stopped
        environment:
            RABBITMQ_DEFAULT_USER: "${RABBITMQ_USER}"
            RABBITMQ_DEFAULT_PASS: "${RABBITMQ_PASSWORD}"
            RABBITMQ_DEFAULT_VHOST: "${RABBITMQ_VHOST}"
            RABBITMQ_ERLANG_COOKIE: "${RABBITMQ_ERLANG_COOKIE}"
        volumes:
            - "${VOLUME_BASE_PATH}/rabbitmq/events:/var/lib/rabbitmq"
        networks:
            - taiga

    taiga-protected:
        image: taigaio/taiga-protected:latest
        container_name: taiga-protected
        restart: unless-stopped
        environment:
            MAX_AGE: 360
            SECRET_KEY: "${RABBITMQ_SECRET_KEY}"
        networks:
            - taiga

    taiga-gateway:
        image: nginx:1.19-alpine
        container_name: taiga-gateway
        restart: unless-stopped
        ports:
            - "9000:80"
        volumes:
            - "${VOLUME_BASE_PATH}/gateway/taiga.conf:/etc/nginx/conf.d/default.conf"
            - "${VOLUME_BASE_PATH}/resources/static:/taiga/static"
            - "${VOLUME_BASE_PATH}/resources/media:/taiga/media"
        networks:
            - taiga
        depends_on:
            - taiga-frontend
            - taiga-backend
            - taiga-events

networks:
    taiga:
